times = ('Palmeiras','Internacional','Flamengo','Corinthians','Fluminense','Atlético-MG','São Paulo','América-MG','Fortaleza','Botafogo','Santos','Bragantino','Goiás','Coritiba','Atlético-GO','Cuiabá','Avaí','Juventude')
print('-='*15)
print (f'Os cincos primeiros times são: {times[0:5]}')
print('-='*15)
print(f'Os últimos 4 colocados são: {times[-4:]}')
print('-='*15)
print (f'Os times em ordem alfabetica e: {sorted(times)}')
print('-='*15)
print(f'A Chapecoense não esta nesta lista mostrarei outro, o Santos {times.index("Santos")+1}° posição')
